# syntax = docker/dockerfile:1.11-labs

FROM input AS fmt
ARG rust_toolchain="nightly"
ARG RUSTUP_HOME
ARG CARGO_HOME
ARG fmt_args=""
ARG sched_policy="--rr"
ARG sched_prio=1

WORKDIR /usr/src/tuwunel
ENV sched_policy=${sched_policy}
ENV sched_prio=${sched_prio}
RUN <<EOF
    set -eux
    rustup run ${rust_toolchain} sched_wrap.sh \
        cargo fmt \
            --all \
            --check \
            --manifest-path Cargo.toml \
            ${fmt_args}
EOF
